---
language: python
python: "2.7"
sudo: required
dist: trusty

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  # Install Ansible.
  - apt-get install python-pip python-dev git -y
  - pip install PyYAML jinja2 paramiko
  - git clone https://github.com/ansible/ansible.git /opt/ansible
  - cd /opt/ansible && make install
  - mkdir /etc/ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install ansible-lint
  - pip install ansible-lint

  # Install requirements
  #- ansible-galaxy install tschifftner.ansible-source

script:
  # Check the role/playbook's syntax.
  #- "ansible-playbook -i tests/inventory tests/prepare.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Prepare by installing required ansible 2.0.0
  #- "ansible-playbook -i tests/inventory tests/prepare.yml --connection=local --sudo"

  - ansible --version

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # ansible-lint checks for best practice
  - ansible-lint tests/$SITE

  # check kibana ist reachable
  - curl http://127.0.0.1:5601/app/kibana

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/