---
- name: Setup Kibana
  include: install.yml
  tags: ['kibana-install']

- name: Import Dashboards, Searches and Visualizations
  include: import.yml
  when: kibana_es_import_files | length
  tags: ['kibana-include']